package com.rajeshpatkar;

import java.io.IOException;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebFilter;
import javax.servlet.annotation.WebInitParam;

@WebFilter(filterName = "F2", servletNames = {"S2"}, initParams = {
    @WebInitParam(name = "fmsg", value = "Hello from Filter F2")})

public class F2 implements Filter {
    
    private FilterConfig fc = null;

    
    @Override
    public void init(FilterConfig fc) throws ServletException {
        this.fc = fc;
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, 
            FilterChain chain) throws IOException, ServletException {
        doBeforeProcessing(request, response);
        chain.doFilter(request, response);
        doAfterProcessing(request, response);
    }

    @Override
    public void destroy() {
        
    }

    private void doBeforeProcessing(ServletRequest request, 
            ServletResponse response) throws ServletException, IOException{
        String msg = fc.getInitParameter("fmsg");
        response.getOutputStream().println(
            "<h5>Header generated by Filter F2</h5>" 
                    + "<br/>" 
                    + "<h6>FilterConfig parameter fmsg = " 
                    + msg
                    + "</h6>"
        );
        request.setAttribute("fmsg", msg);
    }

    private void doAfterProcessing(ServletRequest request, 
            ServletResponse response) throws ServletException, IOException{
        response.getOutputStream().println(
            "<h6>F2 read Attribute msg from Request with value: " 
                    + request.getAttribute("fmsg")
                    + "</h6>" 
                    + "<br/>" 
                    + "<h5>Footer gengrated by Filter F2</h5>"
        );
    }
    
}