package com.rajeshpatkar;

import java.io.IOException;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebFilter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebFilter(filterName = "F1", urlPatterns = {"/*"})
public class F1 implements Filter {

    private FilterConfig filterConfig = null;

    public F1() {
    }

    private void doBeforeProcessing(
            ServletRequest request,
            ServletResponse response)
            throws IOException,
            ServletException 
    {
          response.getOutputStream().println(
                  "<p> Header generated by Filter F1</p>"
          );
    }

    private void doAfterProcessing(
            ServletRequest request,
            ServletResponse response)
            throws IOException, ServletException {
          response.getOutputStream().println(
                  "<p> Footer generated by Filter F1</p>"
          );
    }

    @Override
    public void doFilter(
            ServletRequest request,
            ServletResponse response,
            FilterChain chain)
            throws IOException, ServletException {

        doBeforeProcessing(request, response);
        HttpServletRequest req = (HttpServletRequest) request;
        HttpServletResponse res = (HttpServletResponse) response;
        Throwable problem = null;
        try {
            chain.doFilter(req, res);
        } catch (Exception t) {
            response.getOutputStream().println("error");
        }
        response.getOutputStream().println("here");
            doAfterProcessing(request, response);

    }
    @Override
    public void destroy() {
   
    }
    @Override
    public void init(FilterConfig filterConfig) {
          this.filterConfig = filterConfig;
    }
}