package com.rajeshpatkar;

import java.io.IOException;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebFilter;
import javax.servlet.annotation.WebInitParam;

@WebFilter(filterName= "F2", servletNames = {"S2"}, initParams = {
    @WebInitParam(name = "fmsg", value = "Hello from Filter F3")
})

public class F2 implements Filter{
    
    private FilterConfig filterConfig = null;

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        this.filterConfig = filterConfig;
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, 
            FilterChain chain) throws IOException, ServletException {
        doBeforeProcessing(request, response);
        chain.doFilter(request, response);
        doAfterProcessing(request, response);
    }

    @Override
    public void destroy() {
        
    }

    private void doBeforeProcessing(ServletRequest request, 
            ServletResponse response) throws ServletException, IOException{
        response.getOutputStream().println("<h3>Header generated by Filter F2</h3>");
        String str = filterConfig.getFilterName();
        String msg = filterConfig.getInitParameter("fmsg");
        response.getOutputStream().println(
                "<h4>FilterConfig parameter of Filter "
                        + str
                        + " fmsg is " 
                        + msg
                        + "</h4>"
        );
        request.setAttribute("fmsg", msg);
    }

    private void doAfterProcessing(ServletRequest request, 
            ServletResponse response) throws ServletException, IOException {
        response.getOutputStream().println(
                "<h4>Filter F2 read Attribute msg from request with value = " 
                        + request.getAttribute("fmsg")
                        + "</h4>");
        
        response.getOutputStream().println("<h3>Footer generated by Filter F2</h3>");
    }
    
}
